application:
  location: config (Github)
  config:
    profile: dev
    description: valor obtenido desde "ms-customer.yml"
spring:
  data:
    mongodb:
      database: customer
      host: localhost
      port: 27017
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, refresh, restart, env
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    refresh:
      enabled: true
    restart:
      enabled: true
    env:
      enabled: true